# Notes for  _Linear Algebra: An In-Depth Introduction with a Focus on Applications_
***

### For a matrix (or the coefficient matrix of a linear equation system), we have the following relationshiop:
$$\#\_of\_columns=dim(Columns\_Space)+dim(Null\_Space)$$

$\vec{0}$ is linearly dependent, since there exist a non-trivial linear combination satisfying $\vec{0}=1$

### For the linear equation system $A \cdot \vec{x}=\vec{b}$
__1. Is there any solution?__<br />
If $\vec{b}$ can be expressed as a linear conbination of the column vectors of $A$, there is one or more solution. Ohterwise, no solution. (If $\vec{b}$ is in the space spanned by the column vectors of $A$).
   
__2. Is the solution unique? (Assume the system is solvable)__<br />
If all the column vectors of $A$ are linearly independent, the solution is unique. Otherwise, more than one solutions.


>If the column vectors of $A$ is linearly independent, we have $\#\_of\_columns=dim(Columns\_Space)$. So $dim(Null\_Space)=0$. This conresponds the case of unique solution.

>If the column vectors of $A$ is linearly dependent, $dim(Null\_Space)\ne 0$. We can add any vector in Null Space to the solution, resulting is a new solution to the system. That's why the solution is no unique.

>All the solutions for $A \cdot \vec{x}=\vec{b}$ consist of a unique solution for $A \cdot \vec{x}=\vec{b}$ plus the Null Space of the matrix $A$ (i.e. the general solution for $A \cdot \vec{x}=\vec{0}$).

__An Example of extreme cases:__ <br \>
$0 \cdot x = 0$ ---Solvable. Infinite solutions. <br \>
$3 \cdot x = 0$ ---Solvable. Unique solution. <br />
$3 \cdot x = 3$ ---Solvable. Unique solution. <br />
$0 \cdot x = 3$ ---Solvable. Unsolvable.

***


### Property of Gaussian Elimination
- Gaussian elimination doesn't change the Null Space
- Gaussian elimination will change the Column Space

For Example:

Consider this matrix
$$A =
\begin{bmatrix}
    10 & 2 & 14 & 20 & 8 \\
    3 & 5 & 23 & 6 & -2 \\
    13 & 7 & 27 & 26 & 6 \\ 
\end{bmatrix} \qquad
A\_Column\_Space=
\begin{bmatrix}
    a \\
    b \\
    a+b \\ 
\end{bmatrix}
$$
<br />
After Guassian elimination, the matrix is
$$ A\_G\_Elim = 
\begin{bmatrix}
    1 & 0 & 1 & 2 & 1 \\
    0 & 1 & 2 & 0 & -1 \\
    0 & 0 & 0 & 0 & 0 
\end{bmatrix}\qquad
Column\_Space = 
\begin{bmatrix}
    a \\
    b \\
    0 \\ 
\end{bmatrix}
$$

The column space is changed

***

### Understanding the Row Reduced Echelon Form (RREF) 
This RREF shows the following relationship very clearlyand directly: 
$$\#\_of\_columns=dim(Columns\_Space)+dim(Null\_Space)$$

The columns in matrix $A$ can be divided into to types: <br \>
__1. The columns linearly independent of the previouse columns__ <br \>
This kind of columns contributes to the COLUMN space.

__2. The columns linearly dependent of the previouse columns__ <br \>
This kind of columns contributes to the NULL space.

Example:
$$ A = 
\begin{bmatrix}
1 & 2 & 0 & 0 & 2 & 3 & 0 & 7 \\
0 & 0 & 0 & 1 & 3 & 4 & 0 & 8 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 3 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 
\end{bmatrix}
$$
> For matrix $A$, when we look for the null space, we only care about column 2, 3, 5, 6 and 8. Column 1, 4 and 7 span the column space. 
So the dimension of its column space is 3, and the dimension of the null space is 5. the null space is:
$$ A\_Null = \alpha \cdot
\begin{bmatrix}
2 \\
-1 \\
0 \\
0 \\
0 \\
0 \\
0 \\
0 \\
\end{bmatrix} \quad
+ \beta \cdot
\begin{bmatrix}
0 \\
0 \\
1 \\
0 \\
0 \\
0 \\
0 \\
0 \\
\end{bmatrix} \quad
+ \gamma \cdot
\begin{bmatrix}
2 \\
0 \\
0 \\
3 \\
-1 \\
0 \\
0 \\
0 \\
\end{bmatrix} \quad
+ \delta \cdot
\begin{bmatrix}
3 \\
0 \\
0 \\
4 \\
0 \\
-1 \\
0 \\
0 \\
\end{bmatrix} \quad
+ \epsilon \cdot
\begin{bmatrix}
7 \\
0 \\
0 \\
8 \\
0 \\
0 \\
3 \\
-1 \\
\end{bmatrix} \quad
$$

***

### Understanding Matrix Mulitplication

Matrix multiplication is to find the linear combination of column vectors of the matrix in the left, specific to the coefficients in the matrix in the left. 

Example
$$
\begin{bmatrix}
2 & 3 & 1 \\
4 & 4 & 2 \\
1 & 2 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
3 \\
2 \\
2\\
\end{bmatrix}
=
3 \cdot 
\begin{bmatrix}
2 \\
4 \\
1 \\
\end{bmatrix}
+ 2 \cdot 
\begin{bmatrix}
3 \\
4 \\
2 \\
\end{bmatrix}
+ 2 \cdot
\begin{bmatrix}
1 \\
2 \\
1 \\
\end{bmatrix}
=
\begin{bmatrix}
14 \\
24 \\
9 \\
\end{bmatrix}
$$

That is to say, if we have a vector which is 
$
\begin{bmatrix}
3 \\
2 \\
2 \\
\end{bmatrix}
$
in the coordinates system of 
$
\Bigg(
\begin{bmatrix}
2 \\
4 \\
1 \\
\end{bmatrix},
\begin{bmatrix}
3 \\
4 \\
2 \\
\end{bmatrix},
\begin{bmatrix}
1 \\
2 \\
1 \\
\end{bmatrix}
\Bigg)
$. 
If we want to express it in the common coordinate system 
$
\Bigg(
\begin{bmatrix}
1 \\
0 \\
0 \\
\end{bmatrix},
\begin{bmatrix}
0 \\
1 \\
0 \\
\end{bmatrix},
\begin{bmatrix}
0 \\
0 \\
1 \\
\end{bmatrix}
\Bigg)
$,
it would be 
$
\begin{bmatrix}
14 \\
24 \\
9 \\
\end{bmatrix}
$.

#### Row perspective
$$
\begin{bmatrix}
1 & 2 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
2 & 2 & 1 \\
3 & 1 & 1 \\
3 & 1 & 2 \\
\end{bmatrix}
= 1 \cdot 
\begin{bmatrix}
2 & 2 & 1 \\
\end{bmatrix}
+ 2 \cdot
\begin{bmatrix}
3 & 1 & 1 \\
\end{bmatrix}
+ 1 \cdot 
\begin{bmatrix}
3 & 1 & 2 \\
\end{bmatrix}
=
\begin{bmatrix}
11 & 5 & 5 \\
\end{bmatrix}
$$

***

If we have $A \cdot B = C$ ($A$, $B$ and $C$ are matrices), we have the following relationship:
$$R_A \supseteq R_C$$
$$N_B \subseteq N_C$$
i.e. <br \>
The column space of $C$ is a subspace of the column space of $A$. <br \>
The null space of $B$ is a subspace of the null space of $C$.

#### Invere and Transpose

$(A \cdot B)^{-1} = B^{-1} \cdot A^{-1}$ (if $A$ and $B$ are invertable) <br \>
$(A \cdot B)^{T} = B^{T} \cdot A^{T}$ <br \>
$A^{T} \cdot A$ is symetric: $(A^{T} \cdot A)^{T} = A^{T} \cdot (A^{T})^{T} = A^{T} \cdot A$
***

### The effect of Elementary Matrix in Matrix Multiplication

When the elementary matrix appears on the left, it works on the rows. When it appears on the right, it works on the columns.
Example:
$$
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
=
\begin{bmatrix}
a+2b & b & c \\
d+2e & e & f \\
g+2h & h & i \\
\end{bmatrix}
$$
<br \>
$$
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{bmatrix}
=
\begin{bmatrix}
a& b & c \\
d+2a & e+2b & f+2c \\
g & h & i \\
\end{bmatrix}
$$

***

### LU decomposition
To do a LU decompostion, we just record the Gaussian elimination procedure useing elementary matrices. 

Example: Consider the matrix
$
A=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 10 \\
\end{bmatrix}
$,
We want to get $A=LU$
<br />
<br />
$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -2 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 0 & 0 \\
-4 & 1 & 0 \\
-7 & 0 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 10 \\
\end{bmatrix}
=
\begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & 0 & 1 \\
\end{bmatrix}
$
<br />
<br />
Then 
<br />
$
U=
\begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & 0 & 1 \\
\end{bmatrix} \qquad \quad
L=
\Bigg(
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -2 & 1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
1 & 0 & 0 \\
-4 & 1 & 0 \\
-7 & 0 & 1 \\
\end{bmatrix}
\Bigg)^{-1}
=
\Bigg(
\begin{bmatrix}
1 & 0 & 0 \\
-4 & 1 & 0 \\
-7 & 0 & 1 \\
\end{bmatrix}
\Bigg)^{-1}
\cdot
\Bigg(
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -2 & 1 \\
\end{bmatrix}
\Bigg)^{-1}
=
\begin{bmatrix}
1 & 0 & 0 \\
4 & 1 & 0 \\
7 & 2 & 1 \\
\end{bmatrix}
$


In [59]:
#Check the previous calculation
import numpy as np
U = np.matrix([[1,2,3],[0,-3,-6],[0,0,1]])
l_2 = np.matrix([[1,0,0],[-4,1,0],[-7,0,1]])
l_1 = np.matrix([[1,0,0], [0,1,0], [0,-2,1]])
L = l_2.getI()*l_1.getI()
print(L)
print(L*U)

from scipy import linalg
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
p, l, u = linalg.lu(A)
print(p.dot(l).dot(u))



[[ 1.  0.  0.]
 [ 4.  1.  0.]
 [ 7.  2.  1.]]
[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.  10.]]
[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.  10.]]
